version: '2'

services:
  app:
    container_name: 'app'
    image: app:latest # TODO edit this file properly
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
#    depends_on:
#      - service1


#  service1:
#    container_name: 'service1'
#    image: pagopadcommonacr.azurecr.io/service1:latest
#    env_file:
#      - .env
#    ports:
#      - 8081:8080

