services:
  redis:
    image: 'redis/redis-stack:latest@sha256:ca1e9182f3f6e1e40a766b1bb72f13fa89b8061477dd7843a79bf53e4b2307ae'
    ports:
      - '6379:6379'
      - '8001:8001'
    networks: 
      - test-network
  kafka-to-redis:
    restart: on-failure
    build: ./kafka-to-redis
    environment:
      - INGESTION_EVENTHUB_HOST=pagopa-d-itn-gps-rtp-integration-evh.servicebus.windows.net:9093
      - INGESTION_EVENTHUB_CONN_STRING=${INGESTION_EVENTHUB_CONN_STRING}
      - INGESTION_EVENTHUB_TOPICS=${INGESTION_EVENTHUB_TOPICS}
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    networks: 
      - test-network
networks: 
  test-network: 
    driver: bridge