microservice-chart:
  namespace: "gps"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-gpd-rtp
    tag: "0.0.0-2-PAGOPA-3068-deploy-dev-uat"
    pullPolicy: Always
  livenessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    handlerType: httpGet
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weuprod.gps.internal.dev.platform.pagopa.it"
    path: /gpd-rtp-service/(.*)
    servicePort: 8080
  serviceAccount:
    name: "gps-workload-identity"
  azure:
    workloadIdentityClientId: <workload-identity-client-id-set-automatically-by-gha>
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    capabilities:
      drop:
        - all
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.25"
    limits:
      memory: "512Mi"
      cpu: "0.25"
  autoscaling:
    enable: true
    minReplica: 3
    maxReplica: 10
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  envConfig:
    APP_NAME: "gpd-rtp"
    APP_ENVIRONMENT: "prod"
    WEBSITE_SITE_NAME: 'gpd-rtp' # required to show cloud role name in application insights
    APP_LOGGING_LEVEL: 'INFO'
    DEFAULT_LOGGING_LEVEL: 'INFO'
    CORS_CONFIGURATION: '{"origins": ["*"], "methods": ["*"]}'
    RTP_KAFKA_BROKER: "pagopa-p-itn-gps-rtp-evh.servicebus.windows.net:9093"
    PAYMENT_OPTION_KAFKA_BROKER: "pagopa-p-itn-observ-gpd-evh.servicebus.windows.net:9093"
    PAYMENT_OPTION_EVENTHUB_COMPLETE_GROUP_ID: "rtp"
    SPRING_DATASOURCE_URL: "jdbc:postgresql://gpd-db.p.internal.postgresql.pagopa.it:5432/apd?sslmode=require&prepareThreshold=0&tcpKeepAlive=true" # TODO
    SPRING_DATASOURCE_TYPE: "org.springframework.jdbc.datasource.SimpleDriverDataSource"
    SCHEMA_NAME: "apd"
    REDIS_PORT: "6380"
    ANONYMIZER_URL_HOST: "placeholder:5000" # TODO
    ANONYMIZER_URL_PATH: "placeholder" # TODO
    DEAD_LETTER_ENDPOINT: "https://pagopapweugpsrtpsa.blob.core.windows.net/"
    DEAD_LETTER_CONTAINER_NAME: "rtp-dead-letter"
    OTEL_SERVICE_NAME: "pagopa-gpd-rtp"
    OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=prod"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_TRACES_EXPORTER: otlp
    OTEL_METRICS_EXPORTER: otlp
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
  envSecret:
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-p-connection-string'
    OTEL_EXPORTER_OTLP_HEADERS: "elastic-apm-secret-token"
    RTP_MESSAGE_OUTPUT_EVENTHUB_CONN_STRING: "ehub-p-tx-rtp-connection-string"
    PAYMENT_OPTION_INPUT_EVENTHUB_CONN_STRING: "payment-option-topic-input-conn-string"
    SPRING_DATASOURCE_USERNAME: "db-apd-user-name"
    SPRING_DATASOURCE_PASSWORD: "db-apd-user-password"
    REDIS_HOSTNAME: "redis-hostname"
    REDIS_PASSWORD: "redis-password"
    SHARED_SUBSCRIPTION_KEY: "redis-password" # TODO
    DEAD_LETTER_CONNECTION_STRING: "rtp-storage-account-connection-string"
  keyvault:
    name: "pagopa-p-gps-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - 'user'
  canaryDelivery:
    create: false
    ingress:
      create: true
      canary:
        type: header
        headerName: X-Canary
        headerValue: canary
        weightPercent: 0
    service:
      create: true
    deployment:
      create: true
      image:
        repository: ghcr.io/pagopa/pagopa-gpd-rtp
        tag: "0.0.0"
        pullPolicy: Always
      envConfig: {}
      envSecret: {}
