name: Update Code

on:
  workflow_run:
    workflows:
      - Auto Deploy
    types:
      - completed


  workflow_dispatch:

permissions:
  contents: write

jobs:
  code:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Update OpenApi and Swagger files
        run: |
          cd ./openapi
          sh ./generate_openapi.sh

      - name: Formatting
        uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
          commit-message: "Google Java format [skip ci]"

      # prepare openapi template for infra repo
      - run: |
          mkdir -p "${GITHUB_WORKSPACE}/infra"
          jq  '."servers"[0]."url" |= "${host}"' "${GITHUB_WORKSPACE}/openapi/openapi.json" > "${GITHUB_WORKSPACE}/infra/_openapi.json.tpl"
          
          # open a PR on infra repo
      - name: Create pull request
        uses: jacopocarlini/action-pull-request-another-repo@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }} # TODO: set this secret in repository
        with:
          source_folder: 'infra'
          destination_repo: 'pagopa/pagopa-infra'
          destination_folder: 'src/your-path-here/v1' # TODO: set the path
          destination_base_branch: 'main'
          destination_head_branch: 'projectName-swagger-update' # TODO: set the name
          user_email: 'github-bot@pagopa.it'
          user_name: 'pagopa-github-bot'
          allow_force_push: 'true'

      # TODO terraform apply to update the new openapi.json

